version: '3.7'

services:
  hits:
    build: .
    ports:
      - 5000:5000
    networks:
      -  devops-5
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - devops-5
    volumes:
      - ./redis-data:/data

volumes:
  redis-data:

networks:
  devops-5:
    driver: bridge
